name: Test

on: [push, pull_request]

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "pypy3"]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install python-coveralls coverage nose mypy

      - name: Setup
        run: python setup.py install

      - name: Test
        run: nosetests --with-coverage

      - name: MyPy
        run: mypy pyfritzhome
